// src/maze/template.svelte
<script lang="ts">
  import { createMaze } from "../../maze/engine/core";
  import { onCodeChange } from "../common/blockly.svelte";
  import Alert from "../components/alert.svelte"; 
  import Renderer from "./engine/Renderer";
  
  export let w: number;
  export let height: number;
  export let desc: string = "迷路の中のアイコンを、ゴールまで導きましょう。";
  export let allowReset: boolean = true;

  const state = {
    maze: createMaze(w, h),
  };

  const goal = { x: w - 1, y: h - 1 };

  // ?????
  const globalFunctions = {
    [CUSTOM_MAZE_STEPFORWARD]: () => {
      const currentCell =
        state.maze[state.self.location.y][state.self.location.x];
      const nextCell = moveInMaze(
        state.maze,
        currentCell,
        state.self.direction
      );
      if (!nextCell || currentCell.walls[state.self.direction])
        throw new Error("壁があるため、進むことができません。");

      state.self = { ...state.self, location: nextCell.location };
      if (nextCell.location.x === goal.x && nextCell.location.y === goal.y) {
        throw new BlocklyEditorMessage("迷路をクリアしました！");
      }
    },
    [CUSTOM_MAZE_CHECKWALL]: (direction: MazeDirection) => {
      return state.maze[state.self.location.y][state.self.location.x].walls[
        rotateDirection(state.self.direction, direction)
      ];
    },
    [CUSTOM_MAZE_TURN]: (to: MazeDirection) => {
      setState({
        ...state,
        self: {
          ...state.self,
          direction: rotateDirection(state.self.direction, to),
        },
      });
    },
  };

  let interval = 500;

  let workspaceAreaRef;
  let highlightBlock;
  let code;

  const interpreter = useBlocklyInterpreter({
    globalFunctions,
    executionInterval: interval,
    onStep: highlightBlock,
  });

  import { Accordion, AccordionItem } from '@skeletonlabs/skeleton';
</script>

    <Grid h="100%" templateColumns="1fr 25rem">
      <div ref={workspaceAreaRef} />
      <div overflow="auto">
        <div p={4}>
          <ExecutionWindow
            interpreter={interpreter}
            interval={interval}
            setInterval={setInterval}
            onStart={() => {
              interpreter.start(getCode());
            }}
            onReset={() => {
              setState({ ...getState(), self: defaultSelf });
            }}
          />
        </div>
        <div my={3} />
        <div p={4}>
          <Alert />
          <div>
            <MazeRenderer
              maze={getState().maze}
              location={getState().self.location}
              direction={getState().self.direction}
            />
          </div>
          {#if allowReset}
            <Button
              leftIcon={<Icon as={RiRestartLine} />}
              onClick={() => {
                setState(createDefaultState(w, h));
              }}
            >
              新しい迷路にする
            </Button>
          {/if}
        </Box>
      </Box>
    </Grid>

// src/maze/template.tsx
import { useMemo, useRef, useState } from "react";
import { useGetSet } from "react-use";
import {
  Box,
  Divider,
  Grid,
  Alert,
  AlertIcon,
  AlertDescription,
  Button,
  Icon,
} from "@chakra-ui/react";
import { RiRestartLine } from "react-icons/ri";
import {
  createMaze,
  Maze,
  MazeDirection,
  MazeDirectionMap,
  moveInMaze,
  rotateDirection,
} from "./engine/maze";
import {
  CUSTOM_MAZE_STEPFORWARD,
  CUSTOM_MAZE_TURN,
  CUSTOM_MAZE_CHECKWALL,
} from "./blocks";
import {
  CUSTOM_COMMON_IF,
  CUSTOM_COMMON_IF_ELSE,
  CUSTOM_COMMON_WHILE_TRUE,
  CUSTOM_COMMON_WHILE,
  CUSTOM_COMMON_DO_UNTIL,
} from "../common/blocks";
import { MazeRenderer } from "./MazeRenderer";
import {
  BlocklyEditorMessage,
  useBlocklyInterpreter,
} from "../common/interpreter";
import { ExecutionWindow } from "../components/ExecutionManager";
import {
  BlocklyToolboxDefinition,
  useBlocklyWorkspace,
} from "../common/blockly";

type MazeWorkspaceStateSelf = {
  location: { x: number; y: number };
  direction: MazeDirection;
};

type MazeWorkspaceState = {
  maze: Maze;
  self: MazeWorkspaceStateSelf;
};

const defaultSelf: MazeWorkspaceStateSelf = {
  location: { x: 0, y: 0 },
  direction: MazeDirectionMap.BOTTOM,
};

function createDefaultState(w: number, h: number): MazeWorkspaceState {
  return ({
    maze: createMaze(w, h),
    self: defaultSelf,
  });
}

const toolboxDefinition: BlocklyToolboxDefinition = {
  type: "flyout",
  blockTypes: [
    CUSTOM_MAZE_STEPFORWARD,
    CUSTOM_MAZE_TURN,
    CUSTOM_MAZE_CHECKWALL,
    CUSTOM_COMMON_IF,
    CUSTOM_COMMON_IF_ELSE,
    CUSTOM_COMMON_WHILE_TRUE,
    CUSTOM_COMMON_WHILE,
    CUSTOM_COMMON_DO_UNTIL,
  ],
};

type Variables = {
  width: number;
  height: number;
  description?: string;
};

export function MazeWorkspace({width: w, height: h, description: desc = "迷路の中のアイコンを、ゴールまで導きましょう。"}: Variables): JSX.Element {
  const [getState, setState] = useGetSet(() => createDefaultState(w, h));
  const goal = useMemo(() => ({ x: w - 1, y: h - 1}), []);

  // ?????
  const globalFunctions = useRef({
    [CUSTOM_MAZE_STEPFORWARD]: () => {
      const state = getState();
      const currentCell =
        state.maze[state.self.location.y][state.self.location.x];
      const nextCell = moveInMaze(
        state.maze,
        currentCell,
        state.self.direction
      );
      if (!nextCell || currentCell.walls[state.self.direction])
        throw new Error("壁があるため、進むことができません。");
      setState({
        ...state,
        self: { ...state.self, location: nextCell.location },
      });
      if (nextCell.location.x === goal.x && nextCell.location.y === goal.y) {
        throw new BlocklyEditorMessage("迷路をクリアしました！");
      }
    },
    [CUSTOM_MAZE_CHECKWALL]: (direction: MazeDirection) => {
      const state = getState();
      return state.maze[state.self.location.y][state.self.location.x].walls[
        rotateDirection(state.self.direction, direction)
      ];
    },
    [CUSTOM_MAZE_TURN]: (to: MazeDirection) => {
      const state = getState();
      setState({
        ...state,
        self: {
          ...state.self,
          direction: rotateDirection(state.self.direction, to),
        },
      });
    },
  }).current;

  const [interval, setInterval] = useState(500);

  const { workspaceAreaRef, highlightBlock, getCode } = useBlocklyWorkspace({
    toolboxDefinition,
  });
  const interpreter = useBlocklyInterpreter({
    globalFunctions,
    executionInterval: interval,
    onStep: highlightBlock,
  });

  return (
    <Grid h="100%" templateColumns="1fr 25rem">
      <div ref={workspaceAreaRef} />
      <Box overflow="auto">
        <Box p={4}>
          <ExecutionWindow
            interpreter={interpreter}
            interval={interval}
            setInterval={setInterval}
            onStart={() => {
              interpreter.start(getCode());
            }}
            onReset={() => {
              setState({ ...getState(), self: defaultSelf });
            }}
          />
        </Box>
        <Divider my={3} />
        <Box p={4}>
          <Alert mb={5}>
            <AlertIcon />
            <AlertDescription>
              {desc}
            </AlertDescription>
          </Alert>
          <Box mb={5}>
            <MazeRenderer
              maze={getState().maze}
              location={getState().self.location}
              direction={getState().self.direction}
            />
          </Box>
          <Button
            leftIcon={<Icon as={RiRestartLine} />}
            onClick={() => {
              setState(createDefaultState(w, h));
            }}
          >
            新しい迷路にする
          </Button>
        </Box>
      </Box>
    </Grid>
  );
}
